--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: anish-webapp
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: anish-webapp
  template: 
    metadata: 
      labels: 
        app: anish-webapp
    spec: 
      containers: 
      - name: anish-webapp
        image: 8857890900/anish_webserver
          
        ports: 
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
            
--- 
apiVersion: v1
kind: Service
metadata: 
  name: anish-webapp
spec: 
  ports: 
    - 
      port: 80
      protocol: TCP
      targetPort: 80
  selector: 
    app: anish-webapp
  type: LoadBalancer
